
version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 autoapp:app
    volumes:
      - .:/usr/src/app
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nwangele_loans_dev
    ports:
      - "5432:5432"

volumes:
  postgres_data:
